const papers = [
  {
    "id": 1,
    "title": "Mathematics For CSE",
    "code": "BMATS101",
    "category": "programming",
    "semester": "1",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1lykWhoLSLbdD66PywFOvqKadpjZnPO41/preview",
    "solutionLink": "https://drive.google.com/file/d/1yI2Fs_AqYSwB55JyYhz8lSvghi1jmKUy/preview",
    "oldPaperLink": "https://drive.google.com/file/d/1dytNuksweWVZ4o0uedFM8wrI0fnxYmBc/preview",
    "popularity": "very-high"
  },
  {
    "id": 2,
    "title": "Applied Physics For CSE",
    "code": "BPHYS102/202",
    "category": "programming",
    "semester": "1",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1EPo4fKtVC-pRv-31K1ngNobA9hJn4kDo/preview",
    "solutionLink": "https://drive.google.com/file/d/1Eq3hyKXbgBeVgPw_rgG5xFsU3pIl9VCA/preview",
    "oldPaperLink": "https://drive.google.com/file/d/1Cj3-3mlvepcXP5lVMqbjlydqMzOYCRgN/preview",
    "popularity": "medium"
  },
  {
    "id": 3,
    "title": "Principle of Programming Using C",
    "code": "BPOP103/203",
    "category": "programming",
    "semester": "1",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1Lyy-k8PAf6fpSkYI3hWjmEwiGHAJyGbj/preview",
    "solutionLink": "https://drive.google.com/file/d/1Gx8ywx2qLVmGyxMlZQSV8sq7s9vcHlRG/preview",
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 4,
    "title": "Indian Constitution",
    "code": "BICOK107",
    "category": "programming",
    "semester": "1",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/17WIR2HLEBRT0QQM4kw1WevirttZs7GeS/preview",
    "solutionLink": null,
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 5,
    "title": "Scientific Foundation Of Health",
    "code": "BSFHK158",
    "category": "basic_science",
    "semester": "1",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1Cac42RDBC9UtXGKfUi5Me14FG-aLc-6W/preview",
    "solutionLink": "https://drive.google.com/file/d/1Cac42RDBC9UtXGKfUi5Me14FG-aLc-6W/preview",
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 6,
    "title": "Introduction to Civil Engineering",
    "code": "BESCK104A",
    "category": "programming",
    "semester": "1",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1QJ4wQU-KobTDanBtL11C0W2cjq-BHShQ/preview",
    "solutionLink": null,
    "oldPaperLink": "https://drive.google.com/file/d/1hgoSu8mT6Z6IkMJfHUSFmGuV9OR-m1Vi/preview",
    "popularity": "medium"
  },
  {
    "id": 7,
    "title": "Mathematics For CSE",
    "code": "BMATS201",
    "category": "programming",
    "semester": "2",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1cWG4jvZRZ2iBJA09t0WRW78dqw2vdm9x/preview",
    "solutionLink": "https://drive.google.com/file/d/1BXyhq4ZiTLbhpIwJHGkRYe60rbJQqQne/preview",
    "oldPaperLink": null,
    "popularity": "very-high"
  },
  {
    "id": 8,
    "title": "Applied Chemistry For CSE",
    "code": "BCHES102/202",
    "category": "programming",
    "semester": "2",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1lnD5TTvI5X_8sng4E0qzT5pGCr74z6LL/preview",
    "solutionLink": "https://drive.google.com/file/d/15WLqIDiaKljyJWdl0XsWBWfB-lTJiiS1/preview",
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 9,
    "title": "Introduction to Python Programming",
    "code": "BPLCK105/205B",
    "category": "programming",
    "semester": "2",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1aylHWxDTEvZ9W3oZDX2vUy3luveUwKlX/preview",
    "solutionLink": null,
    "oldPaperLink": null,
    "popularity": "very-high"
  },
  {
    "id": 10,
    "title": "Computer Aided Engineering Drawing",
    "code": "BCEDK203",
    "category": "basic_science",
    "semester": "2",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1Fc3yVkZZ2aBnQ5fiuGPxHKZ79tDIAgRK/preview",
    "solutionLink": null,
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 11,
    "title": "Samskrutika Kannada",
    "code": "BKSKK207",
    "category": "basic_science",
    "semester": "2",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1WF1xwH9qupTMAh1LQ1jjG6_eW7gLSoU0/preview",
    "solutionLink": null,
    "oldPaperLink": "https://drive.google.com/file/d/1Cac42RDBC9UtXGKfUi5Me14FG-aLc-6W/preview",
    "popularity": "medium"
  },
  {
    "id": 12,
    "title": "Innovation and Design Thinking",
    "code": "BIDTK258",
    "category": "basic_science",
    "semester": "2",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1Cb5HxUCDqcRz9VxyLF6di55NKhlmuYYF/preview",
    "solutionLink": null,
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 13,
    "title": "Introduction to Electrical Engineering",
    "code": "BESCK104/204B",
    "category": "basic_science",
    "semester": "2",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1H0aicsDIdGfwoT3UcZ5XXGyswiwL9PXc/preview",
    "solutionLink": null,
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 14,
    "title": "Mathematics For CSE",
    "code": "BMATS301",
    "category": "basic_science",
    "semester": "3",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1tN6tJ98BmS1r_Z6LagP4S8JS-mqLPTnf/preview",
    "solutionLink": "https://drive.google.com/file/d/1hgCehi2mfVkYhNfveEEZqCgLLoW4RIFF/preview",
    "oldPaperLink": "https://drive.google.com/file/d/1ZlfCQX1dAHU6UERsaOlEiA4PeSKWWNk5/preview",
    "popularity": "very-high"
  },
  {
    "id": 15,
    "title": "Digital Design and Computer Organization",
    "code": "BCS302",
    "category": "core",
    "semester": "3",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1NiPGff-dHUVkhmlroj51BvWtax-2odpG/view?usp=d/preview",
    "solutionLink": "https://drive.google.com/file/d/1xROR5IqItpPVinhNgAJ0RBexaho7LEcE/preview",
    "oldPaperLink": "https://drive.google.com/file/d/1xROR5IqItpPVinhNgAJ0RBexaho7LEcE/preview",
    "popularity": "medium"
  },
  {
    "id": 16,
    "title": "OPERATING SYSTEMS",
    "code": "BCS303",
    "category": "core",
    "semester": "3",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/15HBsmBHnOXNhRycK_8pQ0pfTpUIjplMt/preview",
    "solutionLink": "https://drive.google.com/file/d/1LZTpPvlsoJKFuyVyIseHuRxbVqdIqw9Y/preview",
    "oldPaperLink": "https://drive.google.com/file/d/1enDKUJLGxdjgsEMOuEeNiQFaoQP9m7gN/preview",
    "popularity": "very-high"
  },
  {
    "id": 17,
    "title": "DATA STRUCTURES AND APPLICATIONS",
    "code": "BCS304",
    "category": "core",
    "semester": "3",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1GLq4quNzdSomnGh6Y2ilFvjQuXM9JO6z/preview",
    "solutionLink": "https://drive.google.com/file/d/1NT_kKeN4Z0UiW-OhHwgq-8vxWoW2RRAS/preview",
    "oldPaperLink": "https://drive.google.com/file/d/16hGQQlfOdePqioOpN0oBN8ZbQBAzlA2X/preview",
    "popularity": "very-high"
  },
  {
    "id": 18,
    "title": "Object Oriented Programming with JAVA",
    "code": "BCS306A'",
    "category": "core",
    "semester": "3",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1q05hkIDeTilr4zqIaEwGFD_daN7hpIw5/preview",
    "solutionLink": "https://drive.google.com/file/d/1iVE_rPUCBYQKJU9OKhZ8D_zmI33D8a7T/preview",
    "oldPaperLink": "https://drive.google.com/file/d/1wj3e8ibE2BGqbmyS-CgKRk6_0SDAegF1/preview",
    "popularity": "very-high"
  },
  {
    "id": 19,
    "title": "OBJECT ORIENTED PROGRAMMING with C++",
    "code": "BCS306B",
    "category": "core",
    "semester": "3",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1mNOnt2Tvkegvx-zAvGelFCC4bmwOfIV3/preview",
    "solutionLink": null,
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 20,
    "title": "DATA STRUCTURES LABORATORY",
    "code": "",
    "category": "core",
    "semester": "3",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1WF1xwH9qupTMAh1LQ1jjG6_eW7gLSoU0/preview",
    "solutionLink": null,
    "oldPaperLink": "https://drive.google.com/file/d/1Cac42RDBC9UtXGKfUi5Me14FG-aLc-6W/preview",
    "popularity": "very-high"
  },
  {
    "id": 21,
    "title": "Social Connect & Responsibility",
    "code": "21SCR38",
    "category": "core",
    "semester": "3",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1WF1xwH9qupTMAh1LQ1jjG6_eW7gLSoU0/preview",
    "solutionLink": null,
    "oldPaperLink": "https://drive.google.com/file/d/1Cac42RDBC9UtXGKfUi5Me14FG-aLc-6W/preview",
    "popularity": "medium"
  },
  {
    "id": 22,
    "title": "Analysis & Design of Algorithms",
    "code": "BCS402",
    "category": "core",
    "semester": "4",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1U-laCBUAydCFwnqFW5nmPgGHVWv3lPt1/preview",
    "solutionLink": "https://drive.google.com/file/d/1U-laCBUAydCFwnqFW5nmPgGHVWv3lPt1/preview",
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 23,
    "title": "MICROCONTROLLERS",
    "code": "BCS402",
    "category": "core",
    "semester": "4",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1bFd7GbQA6GycngDouhlvhnjNAoPW6t6q/preview",
    "solutionLink": null,
    "oldPaperLink": "https://drive.google.com/file/d/1aVBwZ8K9iHTS_uTiROIZjYcNovQUbv3b/preview",
    "popularity": "medium"
  },
  {
    "id": 24,
    "title": "DATABASE MANAGEMENT SYSTEM",
    "code": "BCS403",
    "category": "core",
    "semester": "4",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1ZIuMbL4yJbnBgp8NrU-PqwO35udCZlA1/preview",
    "solutionLink": null,
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 25,
    "title": "DISCRETE MATHEMATICAL STRUCTURES",
    "code": "BCS405A",
    "category": "core",
    "semester": "4",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1rFJKUntE4UNWRL1IMg2QjWzkVoeEFeuG/preview",
    "solutionLink": "https://drive.google.com/file/d/1wiliZvzo0-Zc2E_UMZDhXuNa2mKgKjw5/preview",
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 26,
    "title": "GRAPH THEORY",
    "code": "BCS405B",
    "category": "core",
    "semester": "4",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1Jdgxk2UiVeXb-TJJywapMucYhW_HLqj3/preview",
    "solutionLink": "https://drive.google.com/file/d/15m3xXKv-Os6JlQI6QvlTnBet7lI2ynCx/preview",
    "oldPaperLink": "https://drive.google.com/file/d/1Sb3hCekSG3Z9fdEq0H_qRqxTzz7w8XIE/preview",
    "popularity": "medium"
  },
  {
    "id": 27,
    "title": "Analysis & Design of Algorithms Lab",
    "code": "BCSL404",
    "category": "core",
    "semester": "4",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1WF1xwH9qupTMAh1LQ1jjG6_eW7gLSoU0/preview",
    "solutionLink": null,
    "oldPaperLink": "https://drive.google.com/file/d/1Cac42RDBC9UtXGKfUi5Me14FG-aLc-6W/preview",
    "popularity": "medium"
  },
  {
    "id": 28,
    "title": "ARTIFICIAL INTELLIGENCE",
    "code": "BAD402",
    "category": "core",
    "semester": "4",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1o73EvSDKnuy5qcoLitiaCSAYZ4PeMNSu/preview",
    "solutionLink": null,
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 29,
    "title": "BIOLOGY FOR ENGINEERS",
    "code": "BCS405C",
    "category": "basic_science",
    "semester": "4",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1h_udrhNRqd0UiwdM8bVeH_PTXyWsVcKB/preview",
    "solutionLink": null,
    "oldPaperLink": "https://drive.google.com/file/d/1aD7ZjnBroS5GvDCcULUJ-F9mrkRgU826/preview",
    "popularity": "medium"
  },
  {
    "id": 30,
    "title": "Software Engineering & Project Management",
    "code": "BCS501",
    "category": "core",
    "semester": "5",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1TUx_F_ldZje158xHr-7juovCHZanzDQU/preview",
    "solutionLink": "https://drive.google.com/file/d/1aHbJ6mj2m71hYtjnTt-ODAZXLnavDPF4/preview",
    "oldPaperLink": "https://drive.google.com/file/d/1cgqyDznfxuOM3QmEgtWn0-YBiNv3B-il/preview",
    "popularity": "medium"
  },
  {
    "id": 31,
    "title": "COMPUTER NETWORKS",
    "code": "BCS502",
    "category": "core",
    "semester": "5",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1hN5bPv6Ida2mef6CXeJoE4YXCoZ4UfHr/preview",
    "solutionLink": "https://drive.google.com/file/d/10ENVRIXIu0mJDN-9HfkDIyciEWItiXb6/preview",
    "oldPaperLink": "https://drive.google.com/file/d/1MQ0_LjfVOgeB0UFW6LTSnVjy_4Uw-Z0N/preview",
    "popularity": "very-high"
  },
  {
    "id": 32,
    "title": "ARTIFICIAL INTELLIGENCE",
    "code": "BCS525B",
    "category": "core",
    "semester": "5",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1WF1xwH9qupTMAh1LQ1jjG6_eW7gLSoU0/preview",
    "solutionLink": "https://drive.google.com/file/d/1Tk6xZC9hMrbLHgiFaHie5uiMDQ3s5YJ3/preview",
    "oldPaperLink": "https://drive.google.com/file/d/1Cac42RDBC9UtXGKfUi5Me14FG-aLc-6W/preview",
    "popularity": "medium"
  },
  {
    "id": 33,
    "title": "FULL STACK DEVELOPMENT",
    "code": "21CS55",
    "category": "core",
    "semester": "5",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1WF1xwH9qupTMAh1LQ1jjG6_eW7gLSoU0/preview",
    "solutionLink": null,
    "oldPaperLink": "https://drive.google.com/file/d/1Cac42RDBC9UtXGKfUi5Me14FG-aLc-6W/preview",
    "popularity": "medium"
  },
  {
    "id": 34,
    "title": "RESEARCH AND METHO AND IPR",
    "code": "BRMK557",
    "category": "core",
    "semester": "5",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1-30gK3LYRL6J1zgepkqzaOmc4OvD0AnG/preview",
    "solutionLink": "https://drive.google.com/file/d/1BBkuv6CHqrWqP7szFL1uzA3gsXzdntCu/preview",
    "oldPaperLink": "https://drive.google.com/file/d/1-30gK3LYRL6J1zgepkqzaOmc4OvD0AnG/preview",
    "popularity": "medium"
  },
  {
    "id": 35,
    "title": "Environmental Studies",
    "code": "21EV57",
    "category": "elective",
    "semester": "5",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1tW1jd9r3Kof_8Y4SbI592C_BTkrcwL3W/preview",
    "solutionLink": "https://drive.google.com/file/d/1R-hi6-za7sokZhVqQsyKv9m56ge6wDCL/preview",
    "oldPaperLink": "https://drive.google.com/file/d/14fYP5dgZp4EURk-Mr1WeFlWVCeZTeiRt/preview",
    "popularity": "medium"
  },
  {
    "id": 36,
    "title": "Unix System Programming",
    "code": "BCS515C",
    "category": "core",
    "semester": "5",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1Blttayw5q6cGL7OLd1ufoV5hGv5PZLPH/preview",
    "solutionLink": "https://drive.google.com/file/d/1TuS1E1iSPJ7G5vyfcreNjq4_m6O6ZFuQ/preview",
    "oldPaperLink": "https://drive.google.com/file/d/1uLiZKT2rA7GMgqMaYzH7IAGu5KcgOSgv/preview",
    "popularity": "medium"
  },
  {
    "id": 37,
    "title": "THEORY OF COMPUTATION",
    "code": "BCS503",
    "category": "core",
    "semester": "5",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1UqP3Q51_T-0aGTk8QQeBjWSF2y4oeEto/preview",
    "solutionLink": "https://drive.google.com/file/d/1OfbbBXT1eYl-mAruZYJZzNiRotujQe5E/preview",
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 38,
    "title": "Microcontrollers & Embedded Systems",
    "code": "BCO601",
    "category": "core",
    "semester": "6",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1BUbRTKVfkXgLlLsmZ5AqD7ANrvRQzC3D/preview",
    "solutionLink": null,
    "oldPaperLink": "https://drive.google.com/file/d/1BmqvVe8WhNCRsXdVT3K-4x8sJbKWDq0l/preview",
    "popularity": "medium"
  },
  {
    "id": 39,
    "title": "CLOUD COMPUTING",
    "code": "BCS601,BIS613D",
    "category": "core",
    "semester": "6",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1lNZUZNCCaJM33y_kzv3sbJSird2AmCRM/preview",
    "solutionLink": "https://drive.google.com/file/d/1p6_qanjmcbp1z7X9XYrKZxy1dwfSLO4R/preview",
    "oldPaperLink": "https://drive.google.com/file/d/11aOchNzYu0p5nvYKYtoa3iZKG2x-SK6B/preview",
    "popularity": "medium"
  },
  {
    "id": 40,
    "title": "WATER CONSERVATION AND RAIN WATER HARVESTING",
    "code": "BCV654A",
    "category": "core",
    "semester": "6",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1bOrd1-U9omf_IH3ZS5gWPceSfP01O4a8/preview",
    "solutionLink": "https://drive.google.com/file/d/1bOrd1-U9omf_IH3ZS5gWPceSfP01O4a8/preview",
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 41,
    "title": "Natural Language Processing",
    "code": "BAI601",
    "category": "core",
    "semester": "6",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1WF1xwH9qupTMAh1LQ1jjG6_eW7gLSoU0/preview",
    "solutionLink": null,
    "oldPaperLink": "https://drive.google.com/file/d/1Cac42RDBC9UtXGKfUi5Me14FG-aLc-6W/preview",
    "popularity": "medium"
  },
  {
    "id": 42,
    "title": "ARTIFICIAL INTELLIGENCE",
    "code": "21CS69",
    "category": "core",
    "semester": "6",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1o73EvSDKnuy5qcoLitiaCSAYZ4PeMNSu/preview",
    "solutionLink": null,
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 43,
    "title": "BIOLOLY FOR ENGINEERS",
    "code": "21BE70",
    "category": "elective",
    "semester": "6",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1h_udrhNRqd0UiwdM8bVeH_PTXyWsVcKB/preview",
    "solutionLink": null,
    "oldPaperLink": "https://drive.google.com/file/d/1aD7ZjnBroS5GvDCcULUJ-F9mrkRgU826/preview",
    "popularity": "medium"
  },
  {
    "id": 44,
    "title": "Integrated Waste Management for Smart City",
    "code": "21IW64",
    "category": "core",
    "semester": "6",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1S6IqRQY87HsRhsqKC3CWsljih5zQoWt-/preview",
    "solutionLink": "https://drive.google.com/file/d/1RXzRXZKEf3q60oNmuWiCC4bqr8KYhFPa/preview",
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 45,
    "title": "BIG DATA ANALYTICS",
    "code": "BCS714D",
    "category": "core",
    "semester": "7",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1YyscUweUvfoV0BP0RQvrUREgv7mOpmAS/preview",
    "solutionLink": "https://drive.google.com/file/d/1m9VH6NBghr7IWFk2v798RrMbLXeZQahf/preview",
    "oldPaperLink": null,
    "popularity": "medium"
  },
  {
    "id": 46,
    "title": "Cryptography & Network Security",
    "code": "BCO601",
    "category": "core",
    "semester": "7",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/1BzdLI_W8Cw9CrnyoJip_OLKoEQu-fLpg/preview",
    "solutionLink": null,
    "oldPaperLink": "https://drive.google.com/file/d/1OKuuW3HnLFZD6PcGhMvW1FImjnI-8fxo/preview",
    "popularity": "medium"
  },
  {
    "id": 47,
    "title": "CONSERVATION OF NATURAL RESOURCES",
    "code": "BCV755B",
    "category": "core",
    "semester": "7",
    "year": "2024",
    "modelPaperLink": "Khttps://drive.google.com/file/d/1D5X9yRrnZ5T_r-jA0m1TQWOHAA2JyPi/preview",
    "solutionLink": "https://drive.google.com/file/d/1c1RSOovace8BaeF_1LbM_2DTeL4fyKFO/preview",
    "oldPaperLink": "https://drive.google.com/file/d/1-dNfufKKZWO3I4EARVDYSURFB6KMGexz/preview",
    "popularity": "medium"
  },
  {
    "id": 48,
    "title": "Parallel Computing",
    "code": "BCS702",
    "category": "core",
    "semester": "7",
    "year": "2024",
    "modelPaperLink": "https://drive.google.com/file/d/170ExErQsAgDRdAlwd2vRcYSu43RaIgb_/preview",
    "solutionLink": null,
    "oldPaperLink": "https://drive.google.com/file/d/1gigxbfaP9OQJhGRlpmNvRu9H1UgDBcBc/preview",
    "popularity": "medium"
  }
];